# Autogenerated by ReportLab guiedit do not edit
from reportlab.graphics.charts.legends import Legend
from reportlab.graphics.shapes import Drawing, _DrawingEditorMixin, Rect
from reportlab.graphics.charts.lineplots import LinePlot
from reportlab.lib.colors import Color
from reporting.consts.colors import Colors


class FleetCostChart(_DrawingEditorMixin, Drawing):
    def __init__(self, width=400, height=200, *args, **kw):
        Drawing.__init__(self, width, height, *args, **kw)
        self._add(self, LinePlot(), name="chart", validate=None, desc=None)
        self._add(self, Legend(), name="legend", validate=None, desc=None)
        self.width = 772

        # Set up the chart colors and styles
        self.background = Rect(
            0, 0, self.width, self.height, strokeWidth=0, fillColor=Colors.ANTHRACITE
        )
        self.background.fillColor = Colors.ANTHRACITE

        # Set up the chart
        self.chart.y = 20
        self.chart.x = 122
        self.chart.height = 150
        self.chart.width = 540
        self.chart.lines[0].strokeColor = Colors.GOLD
        self.chart.lines[1].strokeColor = Colors.SILVER
        self.chart.lines.strokeWidth = 1.5
        self.legend.colorNamePairs = [
            (Colors.GOLD, "Attacker"),
            (Colors.SILVER, "Defender"),
        ]
        self.legend.x = 690
        self.legend.y = 120
        # self.chart.xValueAxis.xLabelFormat = "{dd}/{mm}/{yy}"
        self.chart.yValueAxis.visibleGrid = 1
        self.chart.yValueAxis.labelTextFormat = "%.1f%%"
        self.chart.yValueAxis.avoidBoundSpace = (10, 0)
        self.legend.fontName = "Helvetica"
        self.legend.fontSize = 10
        self.chart.xValueAxis.labels.fontName = "Helvetica"
        self.chart.yValueAxis.labels.fontName = "Helvetica"
        print(self.chart.data)


if __name__ == "__main__":  # NORUNTESTS
    FleetCostChart().save(formats=["pdf"], outDir=".", fnRoot=None)
